version: "3.8"

services:
    test_runner:
      build:
        context: .
      environment:
        SPRING_PROFILES_ACTIVE: test
        TESTCONTAINERS_HOST_OVERRIDE: 172.17.0.1
      volumes:
        - .m2:/root/.m2
        - /var/run/docker.sock:/var/run/docker.sock
      command: mvn verify

volumes:
  db: