name: Deploy to Host in Hostinger

on: [push]

jobs:
  trigger-build:
    name: Trigger Clone and Build
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /root
            ./run_tests.sh
      - name: Deployment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /root
            ./be_setup.sh
